apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-index
  namespace: hello-http
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Hello</title></head>
      <body style="font-family: sans-serif;">
        <h1>Hello World ðŸ‘‹</h1>
        <p>It is Friday!</p>
      </body>
    </html>
