apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http
  namespace: hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      containers:
      - name: nginx
        image: registry.access.redhat.com/ubi9/nginx-120
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        configMap:
          name: hello-index
