apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"hello-http","namespace":"hello-http"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"hello-http"}},"template":{"metadata":{"labels":{"app":"hello-http"}},"spec":{"containers":[{"image":"nginx:stable","name":"nginx","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"web"}]}],"volumes":[{"configMap":{"name":"hello-index"},"name":"web"}]}}}}
  creationTimestamp: "2026-02-19T13:10:29Z"
  generation: 7
  name: hello-http
  namespace: hello-http
  resourceVersion: "109921"
  uid: d3c93e1b-1064-4053-8d48-ffa1a0eb6c00
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-http
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-19T10:39:18-03:00"
      labels:
        app: hello-http
    spec:
      containers:
      - image: registry.access.redhat.com/ubi9/httpd-24
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: web
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: hello-index
        name: web
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-19T13:30:03Z"
    lastUpdateTime: "2026-02-19T13:30:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-19T13:10:29Z"
    lastUpdateTime: "2026-02-19T13:39:20Z"
    message: ReplicaSet "hello-http-59845f6cfd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
