apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2026-02-19T13:10:51Z"
  generation: 1
  name: hello-http
  namespace: hello-http
  resourceVersion: "97852"
  uid: a7b6f501-e8fc-4261-aa37-39d3b591fab4
spec:
  host: hello-http-hello-http.apps-crc.testing
  port:
    targetPort: http
  to:
    kind: Service
    name: hello-http
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2026-02-19T13:10:51Z"
      status: "True"
      type: Admitted
    host: hello-http-hello-http.apps-crc.testing
    routerCanonicalHostname: router-default.apps-crc.testing
    routerName: default
    wildcardPolicy: None
