apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hello-http","namespace":"hello-http"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"hello-http"}}}
  creationTimestamp: "2026-02-19T13:10:29Z"
  name: hello-http
  namespace: hello-http
  resourceVersion: "97692"
  uid: 288ea8c8-179d-48d4-a205-d7665b197897
spec:
  clusterIP: 10.217.5.170
  clusterIPs:
  - 10.217.5.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-http
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
